name: Python CI/CD Pipeline

on:
  push:
    branches:
      - gh-pages
  pull_request:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m venv venv
        if [[ $RUNNER_OS == 'Windows' ]]; then
          .\venv\Scripts\Activate.ps1
        else
          source venv/bin/activate
        fi
        pip install -r requirements.txt

    - name: Run tests
      run: |
        if [[ $RUNNER_OS == 'Windows' ]]; then
          .\venv\Scripts\Activate.ps1
        else
          source venv/bin/activate
        fi
        pytest

  deploy:
    runs-on: ubuntu-latest  
    needs: build
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Build the app
      run: |
        mkdir -p build
        shopt -s extglob
        cp -r !("build") build/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
