name: Python CI/CD Pipeline

on:
  push:
    branches:
      - gh-pages
  pull_request:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate  # Для Windows используем `venv\Scripts\activate`
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate  # Для Windows используем `venv\Scripts\activate`
        pytest

  deploy:
    runs-on: ubuntu-latest  # Деплой будет выполняться только на Ubuntu, так как GitHub Pages поддерживается на Linux.
    needs: build
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Build the app
      run: |
        mkdir -p build
        shopt -s extglob
        cp -r !("build") build/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
